import { StyleSheet } from 'react-native';
import { colors, moderateScale } from './theme';
import { globalStyles } from './global';

export const styles = StyleSheet.create({
  // ... existing styles ...
  statBoxContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: moderateScale(-4),
    marginBottom: moderateScale(16),
  },
  recentActivityContainer: {
    backgroundColor: colors.background.secondary,
    borderRadius: moderateScale(12),
    padding: moderateScale(16),
    marginBottom: moderateScale(16),
    ...globalStyles.cardShadow,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: moderateScale(12),
  },
  sectionTitle: {
    fontSize: moderateScale(16),
    fontWeight: '600',
    color: colors.text.primary,
    marginBottom: moderateScale(12),
  },
  viewAllText: {
    fontSize: moderateScale(12),
    color: colors.primary,
    fontWeight: '500',
  },
  activityList: {
    marginTop: moderateScale(8),
  },
  quickActionsContainer: {
    backgroundColor: colors.background.secondary,
    borderRadius: moderateScale(12),
    padding: moderateScale(16),
    marginBottom: moderateScale(16),
    ...globalStyles.cardShadow,
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: moderateScale(-4),
  },
  quickActionButton: {
    width: '25%',
    padding: moderateScale(4),
    alignItems: 'center',
    marginBottom: moderateScale(8),
  },
  quickActionIcon: {
    width: moderateScale(48),
    height: moderateScale(48),
    borderRadius: moderateScale(24),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: moderateScale(4),
  },
  quickActionLabel: {
    fontSize: moderateScale(12),
    color: colors.text.primary,
    textAlign: 'center',
  },
  notificationsContainer: {
    backgroundColor: colors.background.secondary,
    borderRadius: moderateScale(12),
    padding: moderateScale(16),
    marginBottom: moderateScale(16),
  },
  notificationItem: {
    flexDirection: 'row',
    paddingVertical: moderateScale(10),
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
  },
  notificationItem_last: {
    borderBottomWidth: 0,
  },
  notificationIcon: {
    width: moderateScale(32),
    height: moderateScale(32),
    borderRadius: moderateScale(16),
    backgroundColor: `${colors.secondary}10`,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: moderateScale(12),
  },
  notificationContent: {
    flex: 1,
  },
  notificationTitle: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: colors.text.primary,
  },
  notificationMessage: {
    fontSize: moderateScale(12),
    color: colors.text.secondary,
    marginTop: moderateScale(2),
  },
  notificationTime: {
    fontSize: moderateScale(10),
    color: colors.text.light,
    marginTop: moderateScale(4),
  },

  // Enhanced User Modal Styles
  userModalOverlay: {
    flex: 1,
    backgroundColor: colors.background.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: moderateScale(20),
  },
  userModalKeyboardContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  userModalContent: {
    backgroundColor: colors.background.secondary,
    borderRadius: moderateScale(20),
    width: '100%',
    maxWidth: moderateScale(420),
    maxHeight: '90%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 15,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  userModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: moderateScale(24),
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
    backgroundColor: colors.background.primary,
    borderTopLeftRadius: moderateScale(20),
    borderTopRightRadius: moderateScale(20),
  },
  userModalHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  userModalHeaderIcon: {
    width: moderateScale(44),
    height: moderateScale(44),
    borderRadius: moderateScale(22),
    backgroundColor: `${colors.primary}15`,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: moderateScale(16),
  },
  userModalTitle: {
    fontSize: moderateScale(20),
    fontWeight: '700',
    color: colors.text.primary,
    letterSpacing: -0.5,
  },
  userModalSubtitle: {
    fontSize: moderateScale(13),
    color: colors.text.secondary,
    marginTop: moderateScale(2),
    fontWeight: '500',
  },
  userModalCloseButton: {
    width: moderateScale(36),
    height: moderateScale(36),
    borderRadius: moderateScale(18),
    backgroundColor: colors.background.secondary,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  userModalBody: {
    flex: 1,
  },
  userModalScrollContent: {
    padding: moderateScale(24),
  },
  userModalInputGroup: {
    marginBottom: moderateScale(20),
  },
  userModalInputLabel: {
    fontSize: moderateScale(15),
    fontWeight: '600',
    color: colors.text.primary,
    marginBottom: moderateScale(10),
    letterSpacing: -0.2,
  },
  userModalRequiredAsterisk: {
    color: colors.error,
    fontSize: moderateScale(15),
  },
  userModalInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background.primary,
    borderRadius: moderateScale(12),
    borderWidth: 1.5,
    borderColor: colors.border.light,
    paddingHorizontal: moderateScale(16),
    height: moderateScale(54),
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  userModalInputFocused: {
    borderColor: colors.primary,
    backgroundColor: `${colors.primary}08`,
    borderWidth: 2,
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  userModalInputError: {
    borderColor: colors.error,
    backgroundColor: `${colors.error}08`,
    borderWidth: 1.5,
  },
  userModalInputIconContainer: {
    width: moderateScale(24),
    height: moderateScale(24),
    justifyContent: 'center',
    alignItems: 'center',
  },
  userModalTextInput: {
    flex: 1,
    fontSize: moderateScale(15),
    color: colors.text.primary,
    marginLeft: moderateScale(12),
     borderColor: 'transparent',
    backgroundColor: 'transparent',
    height: '100%',
    fontWeight: '500',
  },
  userModalErrorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: moderateScale(8),
    marginLeft: moderateScale(4),
  },
  userModalErrorText: {
    fontSize: moderateScale(13),
    color: colors.error,
    marginLeft: moderateScale(6),
    fontWeight: '500',
  },
  userModalInfoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: `${colors.info}10`,
    borderRadius: moderateScale(12),
    padding: moderateScale(16),
    marginTop: moderateScale(8),
    borderWidth: 1,
    borderColor: `${colors.info}20`,
  },
  userModalInfoText: {
    fontSize: moderateScale(13),
    color: colors.info,
    marginLeft: moderateScale(10),
    flex: 1,
    fontWeight: '500',
    lineHeight: moderateScale(18),
  },
  userModalFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    padding: moderateScale(24),
    borderTopWidth: 1,
    borderTopColor: colors.border.light,
    backgroundColor: colors.background.primary,
    borderBottomLeftRadius: moderateScale(20),
    borderBottomRightRadius: moderateScale(20),
    gap: moderateScale(12),
  },
  userModalButtonPrimary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    paddingHorizontal: moderateScale(24),
    paddingVertical: moderateScale(14),
    borderRadius: moderateScale(12),
    minWidth: moderateScale(120),
    gap: moderateScale(8),
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  userModalButtonSecondary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background.secondary,
    borderWidth: 1.5,
    borderColor: colors.border.medium,
    paddingHorizontal: moderateScale(24),
    paddingVertical: moderateScale(14),
    borderRadius: moderateScale(12),
    minWidth: moderateScale(100),
  },
  userModalButtonPrimaryText: {
    fontSize: moderateScale(15),
    fontWeight: '600',
    color: colors.text.white,
    letterSpacing: -0.2,
  },
  userModalButtonSecondaryText: {
    fontSize: moderateScale(15),
    fontWeight: '600',
    color: colors.text.primary,
    letterSpacing: -0.2,
  },

  // Legacy Modal Styles (keeping for compatibility)
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.background.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: moderateScale(20),
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  modalContent: {
    backgroundColor: colors.background.secondary,
    borderRadius: moderateScale(16),
    width: '100%',
    maxWidth: moderateScale(400),
    maxHeight: '90%',
    ...globalStyles.cardShadow,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: moderateScale(20),
    borderBottomWidth: 1,
    borderBottomColor: colors.border.light,
  },
  modalTitle: {
    fontSize: moderateScale(18),
    fontWeight: '700',
    color: colors.text.primary,
  },
  closeButton: {
    width: moderateScale(32),
    height: moderateScale(32),
    borderRadius: moderateScale(16),
    backgroundColor: colors.background.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBody: {
    flex: 1,
    padding: moderateScale(20),
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    padding: moderateScale(20),
    borderTopWidth: 1,
    borderTopColor: colors.border.light,
    gap: moderateScale(12),
  },

  // Legacy Form Styles (keeping for compatibility)
  inputGroup: {
    marginBottom: moderateScale(16),
  },
  inputLabel: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: colors.text.primary,
    marginBottom: moderateScale(8),
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background.primary,
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: colors.border.light,
    paddingHorizontal: moderateScale(12),
    height: moderateScale(48),
  },
  inputError: {
    borderColor: colors.error,
    backgroundColor: `${colors.error}05`,
  },
  textInput: {
    flex: 1,
    fontSize: moderateScale(14),
    color: colors.text.primary,
    marginLeft: moderateScale(8),
    height: '100%',
  },
  errorText: {
    fontSize: moderateScale(12),
    color: colors.error,
    marginTop: moderateScale(4),
    marginLeft: moderateScale(4),
  },

  // Legacy Button Styles (keeping for compatibility)
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: moderateScale(16),
    paddingVertical: moderateScale(12),
    borderRadius: moderateScale(8),
    minWidth: moderateScale(80),
    gap: moderateScale(8),
  },
  buttonPrimary: {
    backgroundColor: colors.primary,
  },
  buttonSecondary: {
    backgroundColor: colors.background.primary,
    borderWidth: 1,
    borderColor: colors.border.medium,
  },
  buttonPrimaryText: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: colors.text.white,
  },
  buttonSecondaryText: {
    fontSize: moderateScale(14),
    fontWeight: '600',
    color: colors.text.primary,
  },

  // Additional Form Elements
  textArea: {
    flex: 1,
    fontSize: moderateScale(14),
    color: colors.text.primary,
    marginLeft: moderateScale(8),
    textAlignVertical: 'top',
    minHeight: moderateScale(80),
    paddingTop: moderateScale(8),
  },
  inputContainerTextArea: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colors.background.primary,
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: colors.border.light,
    paddingHorizontal: moderateScale(12),
    paddingVertical: moderateScale(8),
    minHeight: moderateScale(80),
  },
  selectContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.background.primary,
    borderRadius: moderateScale(8),
    borderWidth: 1,
    borderColor: colors.border.light,
    paddingHorizontal: moderateScale(12),
    height: moderateScale(48),
  },
  selectText: {
    fontSize: moderateScale(14),
    color: colors.text.primary,
    flex: 1,
    marginLeft: moderateScale(8),
  },
  selectPlaceholder: {
    fontSize: moderateScale(14),
    color: colors.text.placeholder,
    flex: 1,
    marginLeft: moderateScale(8),
  },
});